spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.sql.init.encoding=UTF-8

app.security.secret-key=${APP_SECURITY_SECRET_KEY}
app.security.jwt-expiration=${APP_SECURITY_JWT_EXPIRATION}

google.places.api.key=${GOOGLE_PLACES_API_KEY}
google.places.base-url=${GOOGLE_PLACES_BASE_URL}
