spring.profiles.active=dev
spring.application.name=vegan-finder


# Hibernate quote all database identifiers (table names, column names, etc.)
# in generated SQL queries
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Default is true.
spring.data.jpa.repositories.enabled=true
#
#spring.jpa.properties.hibernate.show_sql=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8
